
import type { Metadata } from "next";
import StoreProvider from './storeProvider'
import localFont from "next/font/local";
import "./globals.css";
import { GoogleOAuthProvider } from '@react-oauth/google';
import Wrapper from "./Wrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StoreProvider>
        <Wrapper>
           <GoogleOAuthProvider clientId="218070191450-0bd5g1f1blsr3erb8hl7a8ld0i9odr0i.apps.googleusercontent.com">
           <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            {children}
          </body>
        </GoogleOAuthProvider>
        </Wrapper>
      </StoreProvider>
    </html>
  );
}
